# -*- coding: utf-8 -*-
"""CropRecommendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SVGcLnfZSodBkdDShu00TBVf79_mI3i2
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""#Step 1 Basic EDA(Exploratory Data Analysis)"""

df = pd.read_csv("/content/drive/MyDrive/Datasets/Crop_recommendation.csv")

df

df.head(10)

df.shape

df.isna()

df.isna().sum()

df.dtypes

df.duplicated()

duplicate_count = df.duplicated().sum()
print("Number of duplicate rows:", duplicate_count)

df.nunique()

df.describe()

label_counts = df['label'].value_counts()
label_counts

plt.figure(figsize=(10,5))
label_counts.plot(kind='bar', color='skyblue')
plt.title("Crop Label Distribution")
plt.xlabel("Crop Label")
plt.ylabel("Count")
plt.xticks(rotation=45)
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

df.head(3)

X = df[['N'	,'P'	,'K',	'temperature'	,'humidity',	'ph'	,'rainfall']]

y=df['label']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

X_train

y_train

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train_scaled_df = pd.DataFrame(X_train_scaled,columns=X_train.columns)

X_train_scaled_df

models = {
    "RandomForest":RandomForestClassifier(n_estimators=200,random_state=42),
    "DecisionTree":DecisionTreeClassifier(random_state=42),
    "KNN":KNeighborsClassifier(n_neighbors=5),
    "LogisticRegression":LogisticRegression(max_iter=200,random_state=42),
    "SVC(RBF Kernel)":SVC(kernel='rbf',random_state=42)
}

results=[]
for name,model in models.items():
  if name in ["KNN","LogisticRegression","SVC(RBF Kernel)"]:
    model.fit(X_train_scaled,y_train)
    preds=model.predict(X_test_scaled)
  else:
    model.fit(X_train,y_train)
    preds=model.predict(X_test)

  acc = accuracy_score(y_test,preds)
  results.append((name,acc))

results

results_df = pd.DataFrame(results, columns=["Models","Accuracy"])
results_df

results_df = results_df.sort_values(by="Accuracy",ascending=False)
results_df

import pickle as pkl

best_model = RandomForestClassifier(n_estimators=200,random_state=42)
best_model.fit(X_train,y_train)
preds = best_model.predict(X_test)
acc = accuracy_score(y_test,preds)
print(f"Best Model Accuracy is:",acc)

best_model.classes_

bundle={
    "model":best_model,
    "features_cols":['N','P','K','temperature','humidity','ph','rainfall'],
    "classes":best_model.classes_
}

with open('Crop_recommendation_RF.pkl','wb') as f:
  pkl.dump(bundle,f)
  print("Model saved as Crop_recommendation_RF.pkl")

with open('Crop_recommendation_RF.pkl','rb') as f:
  b = pkl.load(f)
  print(type(b["model"]), b["features_cols"])

sample = {'N':90, 'P':40, 'K':40, 'temperature':20, 'humidity':80, 'ph':7, 'rainfall':200}
X = [[sample[c] for c in b["features_cols"]]]
X

print("Pred: ", b["model"].predict(X)[0])

import sklearn
sklearn.__version__